import React, { createContext, useContext, useState, useEffect } from 'react';

export type Theme = 'light' | 'dark';
export type Language = 'en' | 'hi' | 'bn' | 'ta' | 'te' | 'mr' | 'gu' | 'kn' | 'pa' | 'ml';

export const LANGUAGE_NAMES: Record<Language, string> = {
  en: 'English',
  hi: 'हिन्दी (Hindi)',
  bn: 'বাংলা (Bengali)',
  ta: 'தமிழ் (Tamil)',
  te: 'తెలుగు (Telugu)',
  mr: 'मराठी (Marathi)',
  gu: 'ગુજરાતી (Gujarati)',
  kn: 'ಕನ್ನಡ (Kannada)',
  pa: 'ਪੰਜਾਬੀ (Punjabi)',
  ml: 'മലയാളം (Malayalam)'
};

interface AppContextType {
  theme: Theme;
  toggleTheme: () => void;
  language: Language;
  setLanguage: (lang: Language) => void;
  isTranslating: boolean;
  setIsTranslating: (translating: boolean) => void;
  translatingLanguageName: string;
  t: (key: string) => string;
}

const translations = {
  en: {
    appTitle: "HealthPoint",
    liveSync: "ABDM Live Sync",
    patientPortal: "Patient Portal",
    patientDesc: "Login with your Email, Phone or ABHA ID to record symptoms, review clinical summaries, and prepare for your doctor visit.",
    kioskMode: "Login or Register",
    providerDashboard: "Doctor Dashboard",
    providerDesc: "Access the secure doctor portal to review AI-structured clinical histories, anomalies, and AYUSH parameters.",
    secureLogin: "Login",
    tagline1: "Intelligent Clinical Intake",
    tagline2: "for Modern Healthcare",
    subtitle: "HealthPoint empowers patients to independently record comprehensive medical histories via voice and touch, scan prior records, and generate physician-ready structured summaries before the consultation begins.",
    interactiveIntake: "Interactive Intake",
    chatWithHealthPoint: "Chat with HealthPoint to record your medical history.",
    chatWithMediSwift: "Chat with HealthPoint to record your medical history.",
    chatWithMediKiosk: "Chat with HealthPoint to record your medical history.",
    tapToScan: "Tap to Scan or Upload Files",
    scanDesc: "Scan or upload past prescriptions, lab reports, or discharge summaries for AI extraction.",
    ayushAssessment: "Dashavidha Pariksha",
    ayushDesc: "Include Dashavidha Pariksha parameters in the report.",
    generatingReport: "Generating FHIR Report...",
    reportGenerated: "Report Generated",
    reportSentDesc: "Your interactive clinical history and documents have been structured and sent to your doctor.",
    mediKioskAssistant: "HealthPoint Assistant",
    online: "Online",
    typeResponse: "Type your response...",
    remove: "Remove",
    finishGenerate: "Finish & Generate Report",
    dashavidhaTitle: "Dashavidha Pariksha (Self-Assessment)",
    dashavidhaDesc: "Please provide details for the Ayurvedic assessment. This information helps in determining your Prakriti and current imbalances.",
    aharaShakti: "Appetite / Digestion (Ahara Shakti)",
    vyayamaShakti: "Physical Strength (Vyayama Shakti)",
    sattva: "Mental Constitution (Sattva)",
    samhanana: "Body Build (Samhanana)",
    selectOption: "Select...",
    pravaraStrong: "Strong / Excellent (Pravara)",
    madhyamaModerate: "Moderate / Variable (Madhyama)",
    avaraWeak: "Weak / Poor (Avara)",
    vyayamaPravara: "High (Pravara)",
    vyayamaMadhyama: "Moderate (Madhyama)",
    vyayamaAvara: "Low (Avara)",
    sattvaPravara: "Strong (Pravara)",
    sattvaMadhyama: "Moderate (Madhyama)",
    sattvaAvara: "Weak (Avara)",
    samhananaPravara: "Well built (Pravara)",
    samhananaMadhyama: "Medium (Madhyama)",
    samhananaAvara: "Weak/Loose (Avara)",
    backToHome: "Back to Home",
    patientLoginTitle: "Patient Login",
    abhaSubtitle: "Ayushman Bharat Health Account",
    abhaIdLabel: "ABHA ID",
    abhaIdPlaceholder: "14-digit ABHA ID",
    otpLabel: "OTP",
    otpPlaceholder: "Enter 6-digit OTP",
    authenticating: "Authenticating...",
    doctorLoginTitle: "Doctor Login",
    ayushAuthorized: "Ayush Authorized Provider",
    emailAddressLabel: "Email Address",
    emailPlaceholder: "doctor@hospital.com",
    
    // Home Page & About Us
    aboutTitle: "About HealthPoint",
    aboutDesc: "HealthPoint is an intelligent, patient-facing clinical onboarding platform built to eliminate OPD congestion, bridge language barriers, and empower physicians with structured, actionable health summaries.",
    zeroWaitingTitle: "Zero Waiting Overhead",
    zeroWaitingDesc: "Reduces routine outpatient history-taking from 45 minutes down to an interactive 3-minute self-intake before stepping into the doctor's cabin.",
    multilingualTitle: "Multilingual Empowerment",
    multilingualDesc: "Real-time voice and text intake in Hindi, Bengali, and English, making digital hospital registration accessible to every citizen.",
    privacyTitle: "Data Privacy & Safety",
    privacyDesc: "Compliant with the DPDP Act 2023. Patient records are encrypted and isolated; personal data is strictly never used to train artificial intelligence models.",
    integrativeTitle: "Integrative Medicine",
    integrativeDesc: "Seamlessly unites conventional allopathic intake with classical Ayurvedic Dashavidha Pariksha diagnostics for comprehensive patient care.",
    ayushClinicalScience: "Ayurvedic Clinical Diagnostic Science",
    aboutDashavidhaTitle: "About Dashavidha Pariksha",
    aboutDashavidhaDesc: "Derived from Charaka Samhita (Vimana Sthana 8/94), Dashavidha Pariksha is the comprehensive 10-fold clinical examination for evaluating a patient’s constitution, vitality, and treatment tolerance.",
    diagnosticPillarBadge: "Diagnostic Pillar",
    ofTen: "of 10",
    modernIntegrativeRationale: "Modern Integrative Clinical Rationale",
    nationalDigitalId: "National Digital Health ID",
    whatIsAbhaTitle: "What is an ABHA ID?",
    whatIsAbhaDesc: "Ayushman Bharat Health Account (ABHA) is a unique 14-digit identification number that establishes your digital identity in India's healthcare ecosystem.",
    keyConcept: "1. Key Concept",
    citizenBenefits: "2. Citizen Benefits",
    interactiveDemo: "3. Interactive ABHA Demo",
    keyConceptTitle: "How ABDM Transforms Healthcare Access",
    keyConceptDesc1: "The Ayushman Bharat Digital Mission (ABDM) creates a unified digital backbone, linking clinics, diagnostics, and hospitals seamlessly.",
    keyConceptDesc2: "Through consent-based architecture, citizens can share historical records instantly, avoiding physical file burden.",
    keyConceptDesc3: "Standardized medical formats ensure your reports are readable by any certified healthcare provider across any state.",
    citizenBenefitsTitle: "What It Means for You & Your Family",
    benefit1: "No more carrying bulky physical medical history folders or losing old prescriptions.",
    benefit2: "Secure, paperless verification within seconds at any OPD, reducing registration queues.",
    benefit3: "Full authority over your data. Grants, reviews, or revokes clinical access at any moment.",
    demoCardTitle: "Simulated ABHA Digital Health Card",
    demoCardDesc: "Under ABDM, this card is your universal identifier. It is fully integrated with national registries.",
    demoCardName: "Name: Vikram Malhotra",
    demoCardAbhaNo: "ABHA Number: 14-9872-3456-1029",
    demoCardAddress: "ABHA Address: vikram@abdm",
    demoCardGender: "Gender / Age: Male, 34",
    demoCardPhone: "Mobile: +91 98765 43210",
    clickCopy: "Click to Copy Demo ABHA Number",
    copied: "Copied!",
    faqTitle: "Patient & Clinician FAQs",
    
    // Patient Login Portal
    patientPortalTitle: "Patient Access Portal",
    nationalHealthInteroperability: "National Health Interoperability & Clinical Intake",
    signInLogin: "Sign In / Login",
    registerNewAccount: "Create Account / Register",
    selectIdentifierType: "Choose Identifier Type",
    emailAddress: "Email Address",
    mobileNumber: "Mobile Number",
    abhaIdNumber: "ABHA ID",
    enterMobileNo: "Enter 10-Digit Mobile Phone Number",
    enterEmailAddress: "Enter Email Address",
    enterAbhaId: "Enter 14-Digit ABHA ID",
    sendVerificationOtp: "Send OTP Verification Code",
    enterOtpSent: "Enter 6-Digit Verification Code",
    confirmVerifyOtp: "Verify OTP & Sign In",
    consentCheckbox: "I consent to share my data and have read the Privacy Policy",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    termsDesc: "Terms of Service: By registering, you agree to comply with hospital triage regulations.",
    privacyDescDetail: "Privacy Policy: Outlining how we safeguard, encrypt, and handle your sensitive personal health data.",
    iAgreeToTerms: "I have read and accept the Terms of Service",
    iAgreeToPrivacy: "I consent to share my data and have read the Privacy Policy",
    close: "Close",
    registerUsing: "Register Using",
    signInUsing: "Sign In Using",
    activeSessionFound: "Active patient session found",
    resume: "Resume",
    startFresh: "Start Fresh",
    change: "Change",
    autoFillOtp: "Auto-fill OTP",
    creatingAccount: "Creating Account...",
    signingIn: "Signing In...",
    verifyRegister: "Verify OTP & Complete Registration",
    consentLegal: "Consent & Legal Acknowledgement",
    dataPrivacyNotice: "Note: Your medical records are encrypted and will not be used to train AI models.",
    aiDisclaimer: "Clinical AI Disclaimer: HealthPoint's intelligent intake assistant helps organize symptoms and vitals for your attending physician. It does not replace direct physician diagnosis or emergency medical care.",
    otpSentTo: "OTP Sent to",
    verificationCode: "Verification Code:",

    // Patient Dashboard & Home
    patientDashboard: "Patient Dashboard",
    welcome: "Welcome",
    welcomeBack: "Welcome back",
    reportMedicalProblem: "Report a Medical Problem",
    startIntakeSession: "Start a new clinical intake session. Provide your symptoms, vitals, and generate a pre-consultation report for your doctor.",
    upcomingAppointments: "Upcoming Appointments",
    noUpcomingAppointments: "No upcoming appointments",
    latestPrescription: "Latest Prescription",
    noPrescriptionsYet: "No prescriptions loaded yet.",
    viewPastReport: "View your generated clinical summaries and previous reports.",
    downloadPdf: "Download PDF",
    downloadTranscript: "Download Transcript",
    recentReports: "Recent Reports",
    noRecentReports: "No clinical reports generated yet. Start an intake above.",
    exitSession: "Exit",
    areYouSureExit: "Are you sure you want to return to the home screen?",
    yesExit: "Exit",
    noCancel: "Cancel",

    // Hospitals Near Me & Ambulance
    hospitalsNearMe: "Hospitals Near Me",
    hospitalsNearMeDesc: "Locate verified hospitals, emergency trauma units, and OPDs near your location categorized by distance.",
    emergencyAmbulance: "Emergency Ambulance",
    emergencyAmbulanceDesc: "Book and dispatch an urgent emergency ambulance to your current location with live route, distance, and ETA tracking on map.",
    within2km: "Within 2 km",
    within5km: "Within 5 km",
    within10km: "Within 10 km",
    allDistances: "All Distances",
    distanceKm: "Distance",
    etaMins: "ETA to Reach",
    bookAmbulance: "Book Emergency Ambulance",
    trackAmbulance: "Live Ambulance Tracker",
    allowLocation: "Allow Location Access",
    locationRequired: "Location Permission Needed",
    locationDesc: "HealthPoint uses open-source OpenStreetMap to find nearby hospitals and navigate ambulances to your exact location.",
    ambulanceDispatched: "Ambulance Dispatched & En Route",
    timeToReach: "Time to Reach You",
    currentDistance: "Distance from You",
    selectLanguage: "Language",
    readScreen: "Read Aloud",
    stopAudio: "Stop Audio",

    // Review Intake Window
    stepPreSubmissionReview: "Step: Pre-Submission Review",
    reviewIntakeTitle: "Review Your Intake Information",
    reviewIntakeSubtitle: "Please verify your personal details, vitals, and complaints before submitting to the doctor's active queue.",
    patientDemographics: "1. Patient Demographics",
    patientFullName: "Patient Full Name",
    ageGender: "Age & Biological Sex",
    bloodGroup: "Blood Group",
    heightWeight: "Height & Weight",
    hospitalDoctor: "Hospital & Consulting Doctor",
    abhaIdDigitalHealth: "ABHA ID / Digital Health ID",
    recordedVitals: "2. Recorded Vital Signs",
    adjustVitalsHint: "You can adjust values here",
    bloodPressure: "Blood Pressure",
    spo2Oxygen: "Oxygen SpO2",
    pulseRate: "Pulse Rate",
    bodyTemperature: "Body Temperature",
    chiefComplaintReportedSymptoms: "3. Chief Complaint & Reported Symptoms",
    noSymptomsYet: "No symptoms reported yet.",
    uploadedPrescriptionsReports: "4. Uploaded Prescriptions & Diagnostic Reports",
    noDocumentsAttached: "No documents attached.",
    submitToDoctorQueue: "Confirm & Submit to Doctor's Queue",
    submittingToQueue: "Submitting to Doctor's Queue...",
    backToDialogue: "Back to Dialogue",
    notRecorded: "Not recorded",
    yearsOld: "years",

    // Appointment Booking Window
    stepScheduleAppointment: "Step: Schedule Appointment",
    bookAppointmentTitle: "Book an Appointment",
    bookAppointmentSubtitle: "Select an available time slot for your consultation with",
    selectConsultationDate: "Select Consultation Date",
    availableTimeSlots: "Available Time Slots",
    morningSlots: "Morning",
    afternoonSlots: "Afternoon",
    eveningSlots: "Evening",
    confirmScheduleAppointment: "Confirm & Schedule Appointment",
    proceedingWithBooking: "Proceeding with Booking...",
    backToQuestions: "Back to Questions",
    slotAlreadyBooked: "Slot already booked",
    selectDateAndSlotPrompt: "Please choose both a consultation date and an available time slot.",

    // Patient Profile Setup & Popups
    patientBasicInfoTitle: "Patient Basic Information",
    patientBasicInfoSubtitle: "Please complete your demographic parameters for your verified medical profile.",
    clinicalDemographicRegistration: "Clinical Demographic Registration",
    fullLegalName: "Full Legal Name",
    ageInYears: "Age (in Years)",
    biologicalSex: "Biological Sex",
    selectBloodGroup: "Select Blood Group",
    chooseBloodGroupPrompt: "Click to choose blood group",
    chooseBiologicalSexPrompt: "Click to choose biological sex",
    heightCm: "Height (cm) (Optional)",
    weightKg: "Weight (kg) (Optional)",
    optionalTag: "Optional",
    saveAndContinue: "Save Details & Continue",
    savingDetails: "Saving Your Details...",
    male: "Male",
    female: "Female",
    intersex: "Intersex",
    others: "Others",
    specifyCustomBloodGroup: "Please specify custom blood group / phenotype",
    specifyCustomSex: "Please specify custom biological sex",
    confirmSelection: "Confirm Selection",
    cancel: "Cancel",

    // Settings Window & Logout Confirmation
    settings: "Settings",
    preferencesAccount: "Preferences & Account",
    specialistPhysician: "Specialist / Physician",
    registeredPatient: "Registered Patient",
    appearanceTheme: "Appearance & Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    abdmLiveSyncActive: "ABDM Live Sync Active",
    abdmSyncDesc: "Encrypted clinical node connection active. M1, M2 & M3 ABDM health standards synchronization enabled.",
    logOut: "Log Out",
    confirmSignOutTitle: "Confirm Sign Out?",
    confirmSignOutDesc: "Are you sure you want to end your current session and return to the home screen?",
    yesSignOut: "Yes, Sign Out",
    staySignedIn: "Stay Signed In",

    // Clinician Dashboard Link / Header
    doctorSession: "Doctor Session",
    acceleratingHealthcareIntake: "Accelerating Healthcare Intake",
    standardizedIdentity: "Standardized Identity",
    standardizedIdentityDesc: "Formatted like 14-9872-3456-1029, linking all diagnostic tests, prescriptions, and discharge summaries across public & private facilities.",
    nationalInteroperability: "National Interoperability",
    nationalInteroperabilityDesc: "Operates under the Ayushman Bharat Digital Mission (ABDM), ensuring standard FHIR compliance and zero loss of prior medical history.",
    patientControl: "100% Patient Control",
    patientControlDesc: "Medical records can only be accessed by an attending doctor after explicit, time-limited OTP or biometric authorization from the patient.",
    paperlessConsultation: "Paperless Consultation",
    paperlessConsultationDesc: "No need to carry bulky physical files, plastic folders, or lost paper prescriptions from previous years.",
    instantHospitalScanShare: "Instant Hospital Scan & Share",
    instantHospitalScanShareDesc: "Quickly scan OPD kiosk QR codes to share demographic data instantly without standing in paper registration queues.",
    accurateDiagnosticTimeline: "Accurate Diagnostic Timeline",
    accurateDiagnosticTimelineDesc: "Doctors instantly see prior blood tests, allergies, and surgical histories, preventing dangerous drug interactions.",
    accessibleViaMobileEmail: "Accessible via Mobile or Email",
    accessibleViaMobileEmailDesc: "Linked securely to your mobile number and Aadhaar/Email for painless one-touch OTP recovery anywhere in India.",
    noSpeechDetected: "No voice detected. Please speak clearly."
  },
  hi: {
    appTitle: "HealthPoint (हेल्थपॉइंट)",
    liveSync: "ABDM लाइव सिंक",
    patientPortal: "मरीज पोर्टल",
    patientDesc: "लक्षण दर्ज करने, पुराने नुस्खे देखने और डॉक्टर परामर्श की तैयारी के लिए लॉगिन या पंजीकरण करें।",
    kioskMode: "लॉगिन या पंजीकरण",
    providerDashboard: "डॉक्टर डैशबोर्ड",
    providerDesc: "AI-संरचित नैदानिक इतिहास, विसंगतियों और आयुष मापदंडों की समीक्षा करने के लिए सुरक्षित प्रदाता पोर्टल तक पहुंचें।",
    secureLogin: "लॉगिन",
    tagline1: "बुद्धिमान नैदानिक सेवन",
    tagline2: "आधुनिक स्वास्थ्य सेवा के लिए",
    subtitle: "HealthPoint मरीजों को आवाज और स्पर्श के माध्यम से स्वतंत्र रूप से व्यापक चिकित्सा इतिहास रिकॉर्ड करने, पूर्व रिकॉर्ड स्कैन करने और परामर्श शुरू होने से पहले चिकित्सक-तैयार संरचित सारांश उत्पन्न करने का अधिकार देता है।",
    interactiveIntake: "इंटरैक्टिव सेवन",
    chatWithHealthPoint: "अपना चिकित्सा इतिहास दर्ज करने के लिए HealthPoint से चैट करें।",
    chatWithMediSwift: "अपना चिकित्सा इतिहास दर्ज करने के लिए HealthPoint से चैट करें।",
    chatWithMediKiosk: "अपना चिकित्सा इतिहास दर्ज करने के लिए HealthPoint से चैट करें।",
    tapToScan: "फ़ाइलें स्कैन या अपलोड करने के लिए टैप करें",
    scanDesc: "एआई निष्कर्षण के लिए पुराने नुस्खे, लैब रिपोर्ट या डिस्चार्ज सारांश को स्कैन या अपलोड करें।",
    ayushAssessment: "आयुर्वेद (आयुष) मूल्यांकन",
    ayushDesc: "रिपोर्ट में दशविध परीक्षा मापदंडों को शामिल करें।",
    generatingReport: "रिपोर्ट तैयार हो रही है...",
    reportGenerated: "रिपोर्ट तैयार हो गई",
    reportSentDesc: "आपका इंटरैक्टिव क्लिनिकल इतिहास और दस्तावेज़ संरचित होकर आपके डॉक्टर को भेज दिए गए हैं।",
    mediKioskAssistant: "HealthPoint सहायक",
    online: "ऑनलाइन",
    typeResponse: "अपना जवाब टाइप करें...",
    remove: "हटाएं",
    finishGenerate: "समाप्त करें और रिपोर्ट तैयार करें",
    dashavidhaTitle: "दशविध परीक्षा (स्व-मूल्यांकन)",
    dashavidhaDesc: "कृपया आयुर्वेदिक मूल्यांकन के लिए विवरण प्रदान करें। यह जानकारी आपकी प्रकृति और वर्तमान असंतुलन को निर्धारित करने में मदद करती है।",
    aharaShakti: "भूख / पाचन (आहार शक्ति)",
    vyayamaShakti: "शारीरिक शक्ति (व्यायाम शक्ति)",
    sattva: "मानसिक गठन (सत्त्व)",
    samhanana: "शरीर की बनावट (संहनन)",
    selectOption: "चुनें...",
    pravaraStrong: "मजबूत / उत्कृष्ट (प्रवर)",
    madhyamaModerate: "मध्यम / परिवर्तनशील (मध्यम)",
    avaraWeak: "कमजोर / खराब (अवर)",
    vyayamaPravara: "उच्च (प्रवर)",
    vyayamaMadhyama: "मध्यम (मध्यम)",
    vyayamaAvara: "निम्न (अवर)",
    sattvaPravara: "मजबूत (प्रवर)",
    sattvaMadhyama: "मध्यम (मध्यम)",
    sattvaAvara: "कमजोर (अवर)",
    samhananaPravara: "गठीला (प्रवर)",
    samhananaMadhyama: "मध्यम (मध्यम)",
    samhananaAvara: "कमजोर/ढीला (अवर)",
    backToHome: "होम पर वापस जाएं",
    patientLoginTitle: "मरीज लॉगिन",
    abhaSubtitle: "आयुष्मान भारत स्वास्थ्य खाता",
    abhaIdLabel: "ABHA आईडी",
    abhaIdPlaceholder: "14-अंकीय ABHA आईडी",
    otpLabel: "ओटीपी",
    otpPlaceholder: "6-अंकीय ओटीपी दर्ज करें",
    authenticating: "प्रमाणित किया जा रहा है...",
    doctorLoginTitle: "डॉक्टर लॉगिन",
    ayushAuthorized: "आयुष अधिकृत प्रदाता",
    emailAddressLabel: "ईमेल पता",
    emailPlaceholder: "doctor@hospital.com",
    
    // Home Page & About Us
    aboutTitle: "HealthPoint के बारे में",
    aboutDesc: "HealthPoint एक बुद्धिमान नैदानिक मंच है जो ओपीडी की भीड़ को समाप्त करने, भाषा की बाधाओं को दूर करने और डॉक्टरों को संरचित स्वास्थ्य सारांश प्रदान करने के लिए बनाया गया है।",
    zeroWaitingTitle: "शून्य प्रतीक्षा समय",
    zeroWaitingDesc: "ओपीडी इतिहास दर्ज करने के 45 मिनट के समय को केवल 3 मिनट के आसान स्वयं-पंजीकरण में बदल देता है।",
    multilingualTitle: "बहुभाषी सशक्तिकरण",
    multilingualDesc: "हिन्दी, बांग्ला और अंग्रेजी में आवाज और टेक्स्ट द्वारा सेवन, जिससे डिजिटल अस्पताल पंजीकरण प्रत्येक नागरिक के लिए सुलभ होता है।",
    privacyTitle: "डेटा गोपनीयता और सुरक्षा",
    privacyDesc: "DPDP अधिनियम 2023 के अनुरूप। मरीजों के रिकॉर्ड एन्क्रिप्टेड और सुरक्षित हैं; व्यक्तिगत डेटा कभी भी AI प्रशिक्षण के लिए उपयोग नहीं होता।",
    integrativeTitle: "एकीकृत चिकित्सा",
    integrativeDesc: "समग्र स्वास्थ्य देखभाल के लिए आधुनिक एलोपैथिक सेवन और शास्त्रीय आयुर्वेदिक दशविध परीक्षा का सहज संयोजन।",
    ayushClinicalScience: "आयुर्वेदिक नैदानिक ​​निदान विज्ञान",
    aboutDashavidhaTitle: "दशविध परीक्षा के बारे में",
    aboutDashavidhaDesc: "चरक संहिता (विमान स्थान 8/94) से उद्धृत, दशविध परीक्षा रोगी की प्रकृति, जीवन शक्ति और उपचार सहनशीलता के मूल्यांकन के लिए व्यापक 10-गुना नैदानिक ​​परीक्षण है।",
    diagnosticPillarBadge: "नैदानिक स्तंभ",
    ofTen: "/ 10",
    modernIntegrativeRationale: "आधुनिक एकीकृत नैदानिक ​​औचित्य",
    nationalDigitalId: "राष्ट्रीय डिजिटल स्वास्थ्य पहचान पत्र",
    whatIsAbhaTitle: "ABHA आईडी क्या है?",
    whatIsAbhaDesc: "आयुष्मान भारत स्वास्थ्य खाता (ABHA) एक विशिष्ट 14-अंकीय पहचान संख्या है जो भारत के स्वास्थ्य सेवा पारिस्थितिकी तंत्र में आपकी डिजिटल पहचान स्थापित करती है।",
    keyConcept: "1. मुख्य अवधारणा",
    citizenBenefits: "2. नागरिक लाभ",
    interactiveDemo: "3. इंटरैक्टिव ABHA डेमो",
    keyConceptTitle: "ABDM स्वास्थ्य सेवा पहुंच को कैसे बदलता है",
    keyConceptDesc1: "आयुष्मान भारत डिजिटल मिशन क्लीनिकों, प्रयोगशालाओं और अस्पतालों को एक सुरक्षित नेटवर्क में जोड़ता है।",
    keyConceptDesc2: "सहमति आधारित प्रणाली के माध्यम से नागरिक अपने पुराने रिकॉर्ड तुरंत साझा कर सकते हैं।",
    keyConceptDesc3: "मानकीकृत प्रारूप सुनिश्चित करते हैं कि आपकी रिपोर्ट किसी भी राज्य में किसी भी डॉक्टर द्वारा पढ़ी जा सके।",
    citizenBenefitsTitle: "आपके और आपके परिवार के लिए इसका क्या अर्थ है",
    benefit1: "भारी फाइलों को ले जाने या पुराने पर्चे खोने की कोई चिंता नहीं।",
    benefit2: "ओपीडी में कुछ ही सेकंड में सुरक्षित, पेपरलेस सत्यापन जिससे कतारें कम होती हैं।",
    benefit3: "अपने डेटा पर पूर्ण अधिकार। कभी भी अनुमति दें या रद्द करें।",
    demoCardTitle: "सिम्युलेटेड ABHA डिजिटल हेल्थ कार्ड",
    demoCardDesc: "ABDM के तहत यह कार्ड आपका सार्वभौमिक स्वास्थ्य पहचान पत्र है।",
    demoCardName: "नाम: विक्रम मल्होत्रा",
    demoCardAbhaNo: "ABHA नंबर: 14-9872-3456-1029",
    demoCardAddress: "ABHA पता: vikram@abdm",
    demoCardGender: "लिंग / आयु: पुरुष, 34 वर्ष",
    demoCardPhone: "मोबाइल: +91 98765 43210",
    clickCopy: "डेमो ABHA नंबर कॉपी करने के लिए क्लिक करें",
    copied: "कॉपी हो गया!",
    faqTitle: "मरीज और चिकित्सक अक्सर पूछे जाने वाले प्रश्न (FAQ)",

    // Patient Login Portal
    patientPortalTitle: "मरीज प्रवेश पोर्टल",
    nationalHealthInteroperability: "राष्ट्रीय स्वास्थ्य अंतःसंचालनीयता और नैदानिक सेवन",
    signInLogin: "साइन इन / लॉगिन",
    registerNewAccount: "नया खाता बनाएं / पंजीकरण",
    selectIdentifierType: "पहचान का तरीका चुनें",
    emailAddress: "ईमेल पता",
    mobileNumber: "मोबाइल नंबर",
    abhaIdNumber: "ABHA आईडी",
    enterMobileNo: "10-अंकीय मोबाइल फोन नंबर दर्ज करें",
    enterEmailAddress: "ईमेल पता दर्ज करें",
    enterAbhaId: "14-अंकीय ABHA आईडी दर्ज करें",
    sendVerificationOtp: "सत्यापन कोड (OTP) भेजें",
    enterOtpSent: "6-अंकीय सत्यापन कोड दर्ज करें",
    confirmVerifyOtp: "OTP सत्यापित करें और साइन इन करें",
    consentCheckbox: "मैं अपने डेटा को साझा करने की सहमति देता/देती हूं और गोपनीयता नीति पढ़ी है",
    termsOfService: "सेवा की शर्तें",
    privacyPolicy: "गोपनीयता नीति",
    termsDesc: "सेवा की शर्तें: पंजीकरण करके, आप अस्पताल के नियमों का पालन करने के लिए सहमत हैं।",
    privacyDescDetail: "गोपनीयता नीति: हम आपके संवेदनशील स्वास्थ्य डेटा की सुरक्षा और एन्क्रिप्शन कैसे करते हैं।",
    iAgreeToTerms: "मैं सेवा की शर्तों को स्वीकार करता/करती हूं",
    iAgreeToPrivacy: "मैं अपने डेटा को साझा करने की सहमति देता/देती हूं",
    close: "बंद करें",
    registerUsing: "इसके द्वारा पंजीकरण करें",
    signInUsing: "इसके द्वारा साइन इन करें",
    activeSessionFound: "सक्रिय मरीज सत्र मिला",
    resume: "जारी रखें",
    startFresh: "नया शुरू करें",
    change: "बदलें",
    autoFillOtp: "स्वचालित रूप से OTP भरें",
    creatingAccount: "खाता बनाया जा रहा है...",
    signingIn: "साइन इन हो रहा है...",
    verifyRegister: "OTP सत्यापित करें और पंजीकरण पूरा करें",
    consentLegal: "सहमति और कानूनी स्वीकृति",
    dataPrivacyNotice: "नोट: आपके मेडिकल रिकॉर्ड एन्क्रिप्टेड हैं और इनका उपयोग AI मॉडल को प्रशिक्षित करने के लिए नहीं किया जाएगा।",
    aiDisclaimer: "क्लिनिकल अस्वीकरण: हेल्थपॉइंट का यह एआई सहायक आपके डॉक्टर के लिए लक्षणों और महत्वपूर्ण संकेतों को व्यवस्थित करता है। यह चिकित्सीय सलाह या आपातकालीन देखभाल का विकल्प नहीं है।",
    otpSentTo: "OTP भेजा गया:",
    verificationCode: "सत्यापन कोड:",

    // Patient Dashboard & Home
    patientDashboard: "मरीज डैशबोर्ड",
    welcome: "स्वागत है",
    welcomeBack: "वापसी पर स्वागत है",
    reportMedicalProblem: "चिकित्सा समस्या की रिपोर्ट करें",
    startIntakeSession: "एक नया नैदानिक परामर्श सत्र शुरू करें। अपने लक्षण, वाइटल दर्ज करें और डॉक्टर के लिए पूर्व-परामर्श रिपोर्ट बनाएं।",
    upcomingAppointments: "आगामी अपॉइंटमेंट्स",
    noUpcomingAppointments: "कोई आगामी अपॉइंटमेंट नहीं है",
    latestPrescription: "नवीनतम नुस्खा",
    noPrescriptionsYet: "अभी तक कोई नुस्खा अपलोड नहीं हुआ है।",
    viewPastReport: "अपने तैयार किए गए नैदानिक सारांश और पिछली रिपोर्ट देखें।",
    downloadPdf: "PDF डाउनलोड करें",
    downloadTranscript: "बातचीत डाउनलोड करें",
    recentReports: "हालिया रिपोर्ट",
    noRecentReports: "अभी तक कोई रिपोर्ट नहीं बनी है। ऊपर से परामर्श शुरू करें।",
    exitSession: "बाहर निकलें",
    areYouSureExit: "क्या आप वाकई होम स्क्रीन पर लौटना चाहते हैं?",
    yesExit: "बाहर निकलें",
    noCancel: "रद्द करें",

    // Hospitals Near Me & Ambulance
    hospitalsNearMe: "मेरे नजदीकी अस्पताल",
    hospitalsNearMeDesc: "दूरी के आधार पर वर्गीकृत अपने स्थान के पास सत्यापित अस्पतालों और ट्रॉमा इकाइयों का पता लगाएं।",
    emergencyAmbulance: "आपातकालीन एम्बुलेंस",
    emergencyAmbulanceDesc: "मानचित्र पर लाइव रूट, दूरी और ईटीए ट्रैकिंग के साथ अपने वर्तमान स्थान पर आपातकालीन एम्बुलेंस बुक करें।",
    within2km: "2 किमी के भीतर",
    within5km: "5 किमी के भीतर",
    within10km: "10 किमी के भीतर",
    allDistances: "सभी दूरियाँ",
    distanceKm: "दूरी",
    etaMins: "पहुंचने का समय",
    bookAmbulance: "आपातकालीन एम्बुलेंस बुक करें",
    trackAmbulance: "लाइव एम्बुलेंस ट्रैकर",
    allowLocation: "स्थान अनुमति दें",
    locationRequired: "स्थान अनुमति आवश्यक है",
    locationDesc: "मेडीस्विफ्ट आस-पास के अस्पतालों को खोजने और आपके स्थान पर एम्बुलेंस भेजने के लिए ओपन-सोर्स मैप का उपयोग करता है।",
    ambulanceDispatched: "एम्बुलेंस रवाना हो चुकी है",
    timeToReach: "आप तक पहुंचने का समय",
    currentDistance: "आपसे दूरी",
    selectLanguage: "भाषा चुनें",
    readScreen: "बोलकर सुनाएं",
    stopAudio: "आवाज रोकें",

    // Review Intake Window
    stepPreSubmissionReview: "चरण: जमा करने से पहले समीक्षा",
    reviewIntakeTitle: "अपनी जानकारी की समीक्षा करें",
    reviewIntakeSubtitle: "डॉक्टर के पास भेजने से पहले कृपया अपनी व्यक्तिगत जानकारी, वाइटल्स और लक्षणों की पुष्टि करें।",
    patientDemographics: "1. मरीज का विवरण",
    patientFullName: "मरीज का पूरा नाम",
    ageGender: "आयु और जैविक लिंग",
    bloodGroup: "रक्त समूह (Blood Group)",
    heightWeight: "ऊंचाई और वजन",
    hospitalDoctor: "अस्पताल और परामर्श डॉक्टर",
    abhaIdDigitalHealth: "ABHA आईडी / डिजिटल स्वास्थ्य आईडी",
    recordedVitals: "2. दर्ज किए गए वाइटल संकेत",
    adjustVitalsHint: "आप यहां मान बदल सकते हैं",
    bloodPressure: "रक्तचाप (BP)",
    spo2Oxygen: "ऑक्सीजन SpO2",
    pulseRate: "नाड़ी की दर (Pulse)",
    bodyTemperature: "शरीर का तापमान",
    chiefComplaintReportedSymptoms: "3. मुख्य शिकायत और लक्षण",
    noSymptomsYet: "अभी तक कोई लक्षण दर्ज नहीं किए गए।",
    uploadedPrescriptionsReports: "4. अपलोड किए गए पर्चे और रिपोर्ट",
    noDocumentsAttached: "कोई दस्तावेज़ संलग्न नहीं है।",
    submitToDoctorQueue: "पुष्टि करें और डॉक्टर की कतार में भेजें",
    submittingToQueue: "डॉक्टर के पास भेजा जा रहा है...",
    backToDialogue: "बातचीत पर वापस जाएं",
    notRecorded: "दर्ज नहीं",
    yearsOld: "वर्ष",

    // Appointment Booking Window
    stepScheduleAppointment: "चरण: अपॉइंटमेंट शेड्यूल करें",
    bookAppointmentTitle: "अपॉइंटमेंट बुक करें",
    bookAppointmentSubtitle: "परामर्श के लिए उपलब्ध समय स्लॉट चुनें:",
    selectConsultationDate: "परामर्श की तारीख चुनें",
    availableTimeSlots: "उपलब्ध समय स्लॉट",
    morningSlots: "सुबह",
    afternoonSlots: "दोपहर",
    eveningSlots: "शाम",
    confirmScheduleAppointment: "अपॉइंटमेंट की पुष्टि करें",
    proceedingWithBooking: "बुकिंग की जा रही है...",
    backToQuestions: "प्रश्नों पर वापस जाएं",
    slotAlreadyBooked: "यह स्लॉट पहले से बुक है",
    selectDateAndSlotPrompt: "कृपया परामर्श की तारीख और उपलब्ध समय स्लॉट दोनों चुनें।",

    // Patient Profile Setup & Popups
    patientBasicInfoTitle: "मरीज की मूल जानकारी",
    patientBasicInfoSubtitle: "अपनी सत्यापित मेडिकल प्रोफाइल के लिए कृपया जनसांख्यिकीय विवरण पूरा करें।",
    clinicalDemographicRegistration: "नैदानिक जनसांख्यिकीय पंजीकरण",
    fullLegalName: "पूरा कानूनी नाम",
    ageInYears: "आयु (वर्षों में)",
    biologicalSex: "जैविक लिंग",
    selectBloodGroup: "रक्त समूह चुनें",
    chooseBloodGroupPrompt: "रक्त समूह चुनने के लिए क्लिक करें",
    chooseBiologicalSexPrompt: "जैविक लिंग चुनने के लिए क्लिक करें",
    heightCm: "ऊंचाई (सेमी) (वैकल्पिक)",
    weightKg: "वजन (किग्रा) (वैकल्पिक)",
    optionalTag: "वैकल्पिक",
    saveAndContinue: "विवरण सहेजें और जारी रखें",
    savingDetails: "विवरण सहेजा जा रहा है...",
    male: "पुरुष (Male)",
    female: "महिला (Female)",
    intersex: "इंटरसेक्स (Intersex)",
    others: "अन्य (Others)",
    specifyCustomBloodGroup: "कृपया अपना विशिष्ट रक्त समूह दर्ज करें",
    specifyCustomSex: "कृपया अपना जैविक लिंग दर्ज करें",
    confirmSelection: "चयन की पुष्टि करें",
    cancel: "रद्द करें",

    // Settings Window & Logout Confirmation
    settings: "सेटिंग्स",
    preferencesAccount: "प्राथमिकताएं और खाता",
    specialistPhysician: "विशेषज्ञ / चिकित्सक",
    registeredPatient: "पंजीकृत मरीज",
    appearanceTheme: "थीम और प्रदर्शन",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    abdmLiveSyncActive: "ABDM लाइव सिंक सक्रिय",
    abdmSyncDesc: "एन्क्रिप्टेड क्लिनिकल नोड कनेक्शन सक्रिय है। M1, M2 और M3 ABDM स्वास्थ्य मानकों का सिंक्रनाइज़ेशन चालू है।",
    logOut: "लॉग आउट करें",
    confirmSignOutTitle: "क्या आप वाकई लॉग आउट करना चाहते हैं?",
    confirmSignOutDesc: "क्या आप अपने वर्तमान सत्र को समाप्त करके होम स्क्रीन पर वापस जाना चाहते हैं?",
    yesSignOut: "हाँ, लॉग आउट करें",
    staySignedIn: "साइन इन रहें",

    // Clinician Dashboard Link / Header
    doctorSession: "डॉक्टर सत्र",
    acceleratingHealthcareIntake: "त्वरित स्वास्थ्य सेवा सेवन",
    standardizedIdentity: "मानकीकृत पहचान",
    standardizedIdentityDesc: "14-9872-3456-1029 की तरह स्वरूपित, सभी नैदानिक परीक्षणों, नुस्खों और डिस्चार्ज सारांशों को जोड़ता है।",
    nationalInteroperability: "राष्ट्रीय अंतःसंचालनीयता",
    nationalInteroperabilityDesc: "आयुष्मान भारत डिजिटल मिशन (ABDM) के तहत संचालित, मानक FHIR अनुपालन सुनिश्चित करता है।",
    patientControl: "100% मरीज का नियंत्रण",
    patientControlDesc: "मरीज की स्पष्ट OTP या बायोमेट्रिक अनुमति के बाद ही डॉक्टर मेडिकल रिकॉर्ड देख सकते हैं।",
    paperlessConsultation: "पेपरलेस परामर्श",
    paperlessConsultationDesc: "भारी फाइलों, प्लास्टिक फोल्डर या पुराने खोए हुए कागजी नुस्खों को ले जाने की आवश्यकता नहीं।",
    instantHospitalScanShare: "तुरंत अस्पताल स्कैन और शेयर",
    instantHospitalScanShareDesc: "कागजी पंजीकरण कतारों में खड़े हुए बिना तुरंत विवरण साझा करने के लिए ओपीडी कियोस्क क्यूआर कोड स्कैन करें।",
    accurateDiagnosticTimeline: "सटीक नैदानिक समयरेखा",
    accurateDiagnosticTimelineDesc: "डॉक्टर तुरंत पुराने रक्त परीक्षण, एलर्जी और सर्जिकल इतिहास देख सकते हैं।",
    accessibleViaMobileEmail: "मोबाइल या ईमेल द्वारा सुलभ",
    accessibleViaMobileEmailDesc: "भारत में कहीं भी आसान OTP पुनर्प्राप्ति के लिए आपके मोबाइल नंबर और आधार/ईमेल से सुरक्षित रूप से जुड़ा हुआ।",
    noSpeechDetected: "कोई आवाज़ नहीं पहचानी गई। कृपया स्पष्ट बोलें।"
  },
  bn: {
    appTitle: "HealthPoint (হেলথপয়েন্ট)",
    liveSync: "ABDM লাইভ সিঙ্ক",
    patientPortal: "রোগী পোর্টাল",
    patientDesc: "লক্ষণ রেকর্ড করতে, আগের প্রেসক্রিপশন স্ক্যান করতে এবং ডাক্তার দেখানোর প্রস্তুতির জন্য আপনার ABHA ID দিয়ে লগইন করুন।",
    kioskMode: "কিয়স্ক মোডে প্রবেশ করুন",
    providerDashboard: "ডাক্তার ড্যাশবোর্ড",
    providerDesc: "AI-গঠিত ক্লিনিক্যাল ইতিহাস, অসঙ্গতি এবং আয়ুষ পরামিতিগুলি পর্যালোচনা করতে সুরক্ষিত প্রোভাইডার পোর্টালে অ্যাক্সেস করুন।",
    secureLogin: "লগইন",
    tagline1: "ইন্টেলিজেন্ট ক্লিনিক্যাল ইনটেক",
    tagline2: "আধুনিক স্বাস্থ্যসেবার জন্য",
    subtitle: "HealthPoint রোগীদের স্বাধীনভাবে ভয়েস এবং স্পর্শের মাধ্যমে ব্যাপক চিকিৎসা ইতিহাস রেকর্ড করতে, পূর্ববর্তী রেকর্ড স্ক্যান করতে এবং পরামর্শ শুরু হওয়ার আগে চিকিৎসক-প্রস্তুত কাঠামোগত সারাংশ তৈরি করার ক্ষমতা দেয়।",
    interactiveIntake: "ইন্টারেক্টিভ ইনটেক",
    chatWithHealthPoint: "আপনার চিকিৎসা ইতিহাস রেকর্ড করতে HealthPoint-এর সাথে চ্যাট করুন।",
    chatWithMediSwift: "আপনার চিকিৎসা ইতিহাস রেকর্ড করতে HealthPoint-এর সাথে চ্যাট করুন।",
    chatWithMediKiosk: "আপনার চিকিৎসা ইতিহাস রেকর্ড করতে HealthPoint-এর সাথে চ্যাট করুন।",
    tapToScan: "ফাইলগুলি স্ক্যান বা আপলোড করতে ট্যাপ করুন",
    scanDesc: "AI নিষ্কাশনের জন্য পুরানো প্রেসক্রিপশন, ল্যাব রিপোর্ট বা স্রাবের সারাংশ স্ক্যান বা আপলোড করুন।",
    ayushAssessment: "আয়ুর্বেদ (আয়ুষ) মূল্যায়ন",
    ayushDesc: "রিপোর্টে দশবিধ পরীক্ষা পরামিতি অন্তর্ভুক্ত করুন।",
    generatingReport: "রিপোর্ট তৈরি হচ্ছে...",
    reportGenerated: "রিপোর্ট তৈরি হয়েছে",
    reportSentDesc: "আপনার ইন্টারেক্টিভ ক্লিনিকাল ইতিহাস এবং নথিগুলি কাঠামোগত এবং আপনার ডাক্তারের কাছে পাঠানো হয়েছে।",
    mediKioskAssistant: "HealthPoint সহকারী",
    online: "অনলাইন",
    typeResponse: "আপনার প্রতিক্রিয়া টাইপ করুন...",
    remove: "মুছুন",
    finishGenerate: "শেষ করুন এবং রিপোর্ট তৈরি করুন",
    dashavidhaTitle: "দশবিধ পরীক্ষা (স্ব-মূল্যায়ন)",
    dashavidhaDesc: "অনুগ্রহ করে আয়ুর্বেদিক মূল্যায়নের জন্য বিবরণ প্রদান করুন। এই তথ্য আপনার প্রকৃতি এবং বর্তমান ভারসাম্যহীনতা নির্ধারণ করতে সাহায্য করে।",
    aharaShakti: "ক্ষুধা / হজম (আহার শক্তি)",
    vyayamaShakti: "শারীরিক শক্তি (ব্যায়াম শক্তি)",
    sattva: "মানসিক গঠন (সত্ত্ব)",
    samhanana: "শরীরের গঠন (সংহনন)",
    selectOption: "নির্বাচন করুন...",
    pravaraStrong: "শক্তিশালী / চমৎকার (প্রবর)",
    madhyamaModerate: "মাঝারি / পরিবর্তনশীল (মধ্যম)",
    avaraWeak: "দুর্বল / খারাপ (অবর)",
    vyayamaPravara: "উচ্চ (প্রবর)",
    vyayamaMadhyama: "মাঝারি (মধ্যম)",
    vyayamaAvara: "নিম্ন (অবর)",
    sattvaPravara: "শক্তিশালী (প্রবর)",
    sattvaMadhyama: "মাঝারি (মধ্যম)",
    sattvaAvara: "দুর্বল (অবর)",
    samhananaPravara: "সুগঠিত (প্রবর)",
    samhananaMadhyama: "মাঝারি (মধ্যম)",
    samhananaAvara: "দুর্বল/শিথিল (অবর)",
    backToHome: "হোমে ফিরে যান",
    patientLoginTitle: "রোগী লগইন",
    abhaSubtitle: "আয়ুষ্মান ভারত স্বাস্থ্য অ্যাকাউন্ট",
    abhaIdLabel: "ABHA আইডি",
    abhaIdPlaceholder: "১৪-সংখ্যার ABHA আইডি",
    otpLabel: "ওটিপি",
    otpPlaceholder: "৬-সংখ্যার ওটিপি লিখুন",
    authenticating: "প্রমাণীকরণ করা হচ্ছে...",
    doctorLoginTitle: "ডাক্তার লগইন",
    ayushAuthorized: "আয়ুষ অনুমোদিত প্রদানকারী",
    emailAddressLabel: "ইমেইল ঠিকানা",
    emailPlaceholder: "doctor@hospital.com",
    
    // Home Page & About Us
    aboutTitle: "HealthPoint সম্পর্কে",
    aboutDesc: "HealthPoint হল একটি বুদ্ধিমান ক্লিনিক্যাল প্ল্যাটফর্ম যা ওপিডি ভিড় দূর করতে এবং ডাক্তারদের সুসংগঠিত সারাংশ প্রদান করতে তৈরি করা হয়েছে।",
    zeroWaitingTitle: "শূন্য অপেক্ষা সময়",
    zeroWaitingDesc: "রুটিন হিস্ট্রি নেওয়ার ৪৫ মিনিটের সময়কে মাত্র ৩ মিনিটের সহজ সেলফ-ইনটেকে রূপান্তরিত করে।",
    multilingualTitle: "বহুভাষিক ক্ষমতায়ন",
    multilingualDesc: "বাংলা, হিন্দি ও ইংরেজিতে রিয়েল-টাইম ভয়েস ও টেক্সট ইনপুট সুবিধা।",
    privacyTitle: "ডেটা গোপনীয়তা ও সুরক্ষা",
    privacyDesc: "DPDP আইন ২০২৩ অনুবর্তী। রোগীর সমস্ত তথ্য সম্পূর্ণ এনক্রিপ্ট করা থাকে এবং AI প্রশিক্ষণে ব্যবহৃত হয় না।",
    integrativeTitle: "সমন্বিত চিকিৎসা",
    integrativeDesc: "আধুনিক অ্যালোপ্যাথিক চিকিৎসা এবং ঐতিহ্যবাহী আয়ুর্বেদিক দশবিধ পরীক্ষার নিখুঁত মেলবন্ধন।",
    ayushClinicalScience: "আয়ুর্বেদিক ক্লিনিক্যাল ডায়াগনস্টিক সায়েন্স",
    aboutDashavidhaTitle: "দশবিধ পরীক্ষা সম্পর্কে",
    aboutDashavidhaDesc: "চরক সংহিতা (বিমান স্থান ৮/৯৪) থেকে উদ্ভূত, দশবিধ পরীক্ষা হলো রোগীর প্রকৃতি, জীবনীশক্তি ও চিকিৎসা সহনশীলতা মূল্যায়নের জন্য পূর্ণাঙ্গ ১০-গুণ ক্লিনিক্যাল পরীক্ষা।",
    diagnosticPillarBadge: "ডায়াগনস্টিক স্তম্ভ",
    ofTen: "/ ১০",
    modernIntegrativeRationale: "আধুনিক সমন্বিত ক্লিনিক্যাল যৌক্তিকতা",
    nationalDigitalId: "জাতীয় ডিজিটাল স্বাস্থ্য পরিচয়পত্র",
    whatIsAbhaTitle: "ABHA আইডি কী?",
    whatIsAbhaDesc: "আয়ুষ্মান ভারত স্বাস্থ্য অ্যাকাউন্ট (ABHA) হল একটি অনন্য ১৪-সংখ্যার সনাক্তকরণ নম্বর যা ভারতের স্বাস্থ্যসেবা ব্যবস্থায় আপনার ডিজিটাল পরিচয় প্রতিষ্ঠা করে।",
    keyConcept: "১. মূল ধারণা",
    citizenBenefits: "২. নাগরিক সুবিধা",
    interactiveDemo: "৩. ইন্টারেক্টিভ ABHA ডেমো",
    keyConceptTitle: "ABDM কীভাবে স্বাস্থ্যসেবা রূপান্তর করে",
    keyConceptDesc1: "আয়ুষ্মান ভারত ডিজিটাল মিশন সমস্ত ক্লিনিক ও হাসপাতালকে একটি নিরবচ্ছিন্ন নেটওয়ার্কে যুক্ত করে।",
    keyConceptDesc2: "সম্মতি-ভিত্তিক ব্যবস্থার মাধ্যমে নাগরিকরা সহজেই তাদের পূর্ববর্তী রেকর্ড শেয়ার করতে পারেন।",
    keyConceptDesc3: "মানসম্মত ফরম্যাট নিশ্চিত করে আপনার রিপোর্ট যেকোনো রাজ্যের যেকোনো ডাক্তারের কাছে বোধগম্য হবে।",
    citizenBenefitsTitle: "আপনার ও আপনার পরিবারের জন্য এর তাৎপর্য",
    benefit1: "ভারী ফাইল বা প্রেসক্রিপশন হারিয়ে যাওয়ার কোনো ভয় নেই।",
    benefit2: "ওপিডিতে মাত্র কয়েক সেকেন্ডে পেপারলেস যাচাইকরণ, যা লাইনে দাঁড়ানোর সময় বাঁচায়।",
    benefit3: "আপনার তথ্যের ওপর পূর্ণ নিয়ন্ত্রণ। যেকোনো সময় অ্যাক্সেস মঞ্জুর বা প্রত্যাহার করুন।",
    demoCardTitle: "সিমুলেটেড ABHA ডিজিটাল স্বাস্থ্য কার্ড",
    demoCardDesc: "ABDM এর অধীনে এই কার্ডটি আপনার সার্বজনীন পরিচয়পত্র।",
    demoCardName: "নাম: বিক্রম মলহোত্রা",
    demoCardAbhaNo: "ABHA নম্বর: 14-9872-3456-1029",
    demoCardAddress: "ABHA ঠিকানা: vikram@abdm",
    demoCardGender: "লিঙ্গ / বয়স: পুরুষ, ৩৪ বছর",
    demoCardPhone: "মোবাইল: +91 98765 43210",
    clickCopy: "ডেমো ABHA নম্বর কপি করতে ক্লিক করুন",
    copied: "কপি হয়েছে!",
    faqTitle: "রোগী ও চিকিৎসকদের সাধারণ প্রশ্নোত্তর (FAQ)",

    // Patient Login Portal
    patientPortalTitle: "রোগী অ্যাক্সেস পোর্টাল",
    nationalHealthInteroperability: "জাতীয় স্বাস্থ্য ইন্টারঅপারেবিলিটি এবং ক্লিনিকাল ইনটেক",
    signInLogin: "সাইন ইন / লগইন",
    registerNewAccount: "নতুন অ্যাকাউন্ট তৈরি / নিবন্ধন",
    selectIdentifierType: "শনাক্তকরণের মাধ্যম বেছে নিন",
    emailAddress: "ইমেইল ঠিকানা",
    mobileNumber: "মোবাইল নম্বর",
    abhaIdNumber: "ABHA আইডি",
    enterMobileNo: "১০-সংখ্যার মোবাইল ফোন নম্বর লিখুন",
    enterEmailAddress: "ইমেইল ঠিকানা লিখুন",
    enterAbhaId: "১৪-সংখ্যার ABHA আইডি লিখুন",
    sendVerificationOtp: "যাচাইকরণ কোড (OTP) পাঠান",
    enterOtpSent: "৬-সংখ্যার যাচাইকরণ কোড লিখুন",
    confirmVerifyOtp: "OTP যাচাই করে সাইন ইন করুন",
    consentCheckbox: "আমি আমার ডেটা শেয়ার করতে সম্মতি দিচ্ছি এবং গোপনীয়তা নীতি পড়েছি",
    termsOfService: "পরিষেবার শর্তাবলী",
    privacyPolicy: "গোপনীয়তা নীতি",
    termsDesc: "পরিষেবার শর্তাবলী: নিবন্ধন করে আপনি হাসপাতালের নিয়ম মেনে চলতে সম্মত হচ্ছেন।",
    privacyDescDetail: "গোপনীয়তা নীতি: আমরা কীভাবে আপনার স্বাস্থ্য তথ্যের নিরাপত্তা রক্ষা করি।",
    iAgreeToTerms: "আমি পরিষেবার শর্তাবলী মেনে নিচ্ছি",
    iAgreeToPrivacy: "আমি আমার তথ্য শেয়ার করতে সম্মতি জানাচ্ছি",
    close: "বন্ধ করুন",
    registerUsing: "এর মাধ্যমে নিবন্ধন করুন",
    signInUsing: "এর মাধ্যমে সাইন ইন করুন",
    activeSessionFound: "সক্রিয় রোগীর সেশন পাওয়া গেছে",
    resume: "চালিয়ে যান",
    startFresh: "নতুন করে শুরু করুন",
    change: "পরিবর্তন",
    autoFillOtp: "স্বয়ংক্রিয়ভাবে OTP পূরণ করুন",
    creatingAccount: "অ্যাকাউন্ট তৈরি হচ্ছে...",
    signingIn: "সাইন ইন হচ্ছে...",
    verifyRegister: "OTP যাচাই করুন এবং নিবন্ধন সম্পন্ন করুন",
    consentLegal: "সম্মতি এবং আইনি স্বীকৃতি",
    dataPrivacyNotice: "নোট: আপনার মেডিকেল রেকর্ডগুলি এনক্রিপ্ট করা হয়েছে এবং AI প্রশিক্ষণের জন্য ব্যবহার করা হবে না।",
    aiDisclaimer: "ক্লিনিক্যাল দাবিত্যাগ: হেলথপয়েন্টের এআই সহকারী আপনার চিকিৎসকের জন্য উপসর্গ ও গুরুত্বপূর্ণ লক্ষণ সংগঠিত করে। এটি চিকিৎসকের সরাসরি পরামর্শ বা জরুরি চিকিৎসার বিকল্প নয়।",
    otpSentTo: "OTP পাঠানো হয়েছে:",
    verificationCode: "যাচাইকরণ কোড:",

    // Patient Dashboard & Home
    patientDashboard: "রোগী ড্যাশবোর্ড",
    welcome: "স্বাগতম",
    welcomeBack: "স্বাগতম",
    reportMedicalProblem: "একটি স্বাস্থ্য সমস্যা রিপোর্ট করুন",
    startIntakeSession: "একটি নতুন ক্লিনিক্যাল পরামর্শ সেশন শুরু করুন। লক্ষণ ও ভাইটাল দিন এবং ডাক্তারের জন্য রিপোর্ট তৈরি করুন।",
    upcomingAppointments: "আসন্ন অ্যাপয়েন্টমেন্ট",
    noUpcomingAppointments: "কোনো আসন্ন অ্যাপয়েন্টমেন্ট নেই",
    latestPrescription: "সাম্প্রতিক প্রেসক্রিপশন",
    noPrescriptionsYet: "এখনও কোনো প্রেসক্রিপশন লোড হয়নি।",
    viewPastReport: "আপনার তৈরি করা ক্লিনিকাল সারাংশ এবং পূর্ববর্তী রিপোর্ট দেখুন।",
    downloadPdf: "PDF ডাউনলোড করুন",
    downloadTranscript: "কথোপকথন ডাউনলোড করুন",
    recentReports: "সাম্প্রতিক রিপোর্ট",
    noRecentReports: "এখনও কোনো রিপোর্ট তৈরি হয়নি। উপরে থেকে শুরু করুন।",
    exitSession: "প্রস্থান",
    areYouSureExit: "আপনি কি নিশ্চিতভাবে হোম স্ক্রিনে ফিরে যেতে চান?",
    yesExit: "প্রস্থান করুন",
    noCancel: "বাতিল",

    // Hospitals Near Me & Ambulance
    hospitalsNearMe: "আমার কাছের হাসপাতাল",
    hospitalsNearMeDesc: "দূরত্ব অনুসারে সাজানো আপনার অবস্থানের কাছাকাছি যাচাইকৃত হাসপাতাল এবং জরুরি সেবা খুঁজুন।",
    emergencyAmbulance: "জরুরী অ্যাম্বুলেন্স",
    emergencyAmbulanceDesc: "মানচিত্রে লাইভ রুট এবং সময় ট্র্যাকিং সহ আপনার অবস্থানে একটি জরুরি অ্যাম্বুলেন্স বুক করুন।",
    within2km: "২ কিমি এর মধ্যে",
    within5km: "৫ কিমি এর মধ্যে",
    within10km: "১০ কিমি এর মধ্যে",
    allDistances: "সব দূরত্ব",
    distanceKm: "দূরত্ব",
    etaMins: "পৌঁছানোর সময়",
    bookAmbulance: "জরুরী অ্যাম্বুলেন্স বুক করুন",
    trackAmbulance: "লাইভ অ্যাম্বুলেন্স ট্র্যাকার",
    allowLocation: "লোকেশন অনুমতি দিন",
    locationRequired: "লোকেশন অনুমতি প্রয়োজন",
    locationDesc: "কাছের হাসপাতাল এবং অ্যাম্বুলেন্স পাঠাতে HealthPoint ওপেন-সোর্স ম্যাপ ব্যবহার করে।",
    ambulanceDispatched: "অ্যাম্বুলেন্স পাঠানো হয়েছে",
    timeToReach: "আপনার কাছে পৌঁছানোর সময়",
    currentDistance: "আপনার থেকে দূরত্ব",
    selectLanguage: "ভাষা নির্বাচন করুন",
    readScreen: "পড়ে শোনান",
    stopAudio: "শব্দ বন্ধ করুন",

    // Review Intake Window
    stepPreSubmissionReview: "ধাপ: জমা দেওয়ার আগে পর্যালোচনা",
    reviewIntakeTitle: "আপনার তথ্য পর্যালোচনা করুন",
    reviewIntakeSubtitle: "ডাক্তারের সক্রিয় সারিতে জমা দেওয়ার আগে অনুগ্রহ করে আপনার ব্যক্তিগত বিবরণ, ভাইটাল এবং অভিযোগ যাচাই করুন।",
    patientDemographics: "১. রোগীর জনসংখ্যাতাত্ত্বিক বিবরণ",
    patientFullName: "রোগীর পুরো নাম",
    ageGender: "বয়স এবং জৈবিক লিঙ্গ",
    bloodGroup: "রক্তের গ্রুপ (Blood Group)",
    heightWeight: "উচ্চতা এবং ওজন",
    hospitalDoctor: "হাসপাতাল এবং পরামর্শক ডাক্তার",
    abhaIdDigitalHealth: "ABHA আইডি / ডিজিটাল স্বাস্থ্য আইডি",
    recordedVitals: "২. রেকর্ড করা ভাইটাল লক্ষণ",
    adjustVitalsHint: "আপনি এখানে মান সমন্বয় করতে পারেন",
    bloodPressure: "রক্তচাপ (BP)",
    spo2Oxygen: "অক্সিজেন SpO2",
    pulseRate: "নাড়ির হার (Pulse)",
    bodyTemperature: "শরীরের তাপমাত্রা",
    chiefComplaintReportedSymptoms: "৩. প্রধান অভিযোগ এবং লক্ষণ",
    noSymptomsYet: "এখনও কোনো লক্ষণ রিপোর্ট করা হয়নি।",
    uploadedPrescriptionsReports: "৪. আপলোড করা প্রেসক্রিপশন এবং রিপোর্ট",
    noDocumentsAttached: "কোনো নথি সংযুক্ত নেই।",
    submitToDoctorQueue: "নিশ্চিত করুন এবং ডাক্তারের সারিতে জমা দিন",
    submittingToQueue: "ডাক্তারের সারিতে জমা দেওয়া হচ্ছে...",
    backToDialogue: "কথোপকথনে ফিরে যান",
    notRecorded: "রেকর্ড করা হয়নি",
    yearsOld: "বছর",

    // Appointment Booking Window
    stepScheduleAppointment: "ধাপ: অ্যাপয়েন্টমেন্ট নির্ধারণ করুন",
    bookAppointmentTitle: "অ্যাপয়েন্টমেন্ট বুক করুন",
    bookAppointmentSubtitle: "পরামর্শের জন্য উপলব্ধ সময় স্লট নির্বাচন করুন:",
    selectConsultationDate: "পরামর্শের তারিখ নির্বাচন করুন",
    availableTimeSlots: "উপলব্ধ সময় স্লট",
    morningSlots: "সকাল",
    afternoonSlots: "দুপুর",
    eveningSlots: "সন্ধ্যা",
    confirmScheduleAppointment: "অ্যাপয়েন্টমেন্ট নিশ্চিত করুন",
    proceedingWithBooking: "বুকিং প্রক্রিয়া চলছে...",
    backToQuestions: "প্রশ্নে ফিরে যান",
    slotAlreadyBooked: "স্লটটি ইতোমধ্যে বুক করা হয়েছে",
    selectDateAndSlotPrompt: "অনুগ্রহ করে পরামর্শের তারিখ এবং একটি উপলব্ধ সময় স্লট উভয়ই নির্বাচন করুন।",

    // Patient Profile Setup & Popups
    patientBasicInfoTitle: "রোগীর মৌলিক তথ্য",
    patientBasicInfoSubtitle: "আপনার যাচাইকৃত মেডিকেল প্রোফাইলের জন্য অনুগ্রহ করে জনসংখ্যাতাত্ত্বিক বিবরণ সম্পূর্ণ করুন।",
    clinicalDemographicRegistration: "ক্লিনিক্যাল ডেমোগ্রাফিক রেজিস্ট্রেশন",
    fullLegalName: "আইনি পুরো নাম",
    ageInYears: "বয়স (বছরে)",
    biologicalSex: "জৈবিক লিঙ্গ",
    selectBloodGroup: "রক্তের গ্রুপ নির্বাচন করুন",
    chooseBloodGroupPrompt: "রক্তের গ্রুপ নির্বাচন করতে ক্লিক করুন",
    chooseBiologicalSexPrompt: "জৈবিক লিঙ্গ নির্বাচন করতে ক্লিক করুন",
    heightCm: "উচ্চতা (সেমি) (ঐচ্ছিক)",
    weightKg: "ওজন (কেজি) (ঐচ্ছিক)",
    optionalTag: "ঐচ্ছিক",
    saveAndContinue: "সংরক্ষণ করুন এবং চালিয়ে যান",
    savingDetails: "তথ্য সংরক্ষণ করা হচ্ছে...",
    male: "পুরুষ (Male)",
    female: "মহিলা (Female)",
    intersex: "ইন্টারসেক্স (Intersex)",
    others: "অন্যান্য (Others)",
    specifyCustomBloodGroup: "অনুগ্রহ করে কাস্টম রক্তের গ্রুপ লিখুন",
    specifyCustomSex: "অনুগ্রহ করে আপনার জৈবিক লিঙ্গ লিখুন",
    confirmSelection: "নির্বাচন নিশ্চিত করুন",
    cancel: "বাতিল",

    // Settings Window & Logout Confirmation
    settings: "সেটিংস",
    preferencesAccount: "পছন্দ এবং অ্যাকাউন্ট",
    specialistPhysician: "বিশেষজ্ঞ / চিকিৎসক",
    registeredPatient: "নিবন্ধিত রোগী",
    appearanceTheme: "থিম ও ডিসপ্লে",
    lightMode: "লাইট মোড",
    darkMode: "ডার্ক মোড",
    abdmLiveSyncActive: "ABDM লাইভ সিঙ্ক সক্রিয়",
    abdmSyncDesc: "এনক্রিপ্ট করা ক্লিনিক্যাল নোড সংযোগ সক্রিয়। M1, M2 এবং M3 ABDM স্বাস্থ্য মান সিঙ্ক্রোনাইজেশন সক্ষম।",
    logOut: "লগ আউট করুন",
    confirmSignOutTitle: "লগ আউট নিশ্চিত করবেন?",
    confirmSignOutDesc: "আপনি কি নিশ্চিতভাবে বর্তমান সেশন শেষ করে হোম স্ক্রিনে ফিরে যেতে চান?",
    yesSignOut: "হ্যাঁ, লগ আউট করুন",
    staySignedIn: "লগইন থাকুন",

    // Clinician Dashboard Link / Header
    doctorSession: "ডাক্তার সেশন",
    acceleratingHealthcareIntake: "দ্রুত স্বাস্থ্যসেবা ইনটেক",
    standardizedIdentity: "মানসম্মত পরিচয়",
    standardizedIdentityDesc: "14-9872-3456-1029 এর মতো ফর্ম্যাট করা, সমস্ত ডায়াগনস্টিক পরীক্ষা ও প্রেসক্রিপশন লিংক করে।",
    nationalInteroperability: "জাতীয় ইন্টারঅপারেবিলিটি",
    nationalInteroperabilityDesc: "আয়ুষ্মান ভারত ডিজিটাল মিশনের (ABDM) অধীনে পরিচালিত, স্ট্যান্ডার্ড FHIR সম্মতি নিশ্চিত করে।",
    patientControl: "১০০% রোগীর নিয়ন্ত্রণ",
    patientControlDesc: "রোগীর স্পষ্ট ওটিপি বা বায়োমেট্রিক অনুমোদনের পরেই ডাক্তার রেকর্ড দেখতে পারেন।",
    paperlessConsultation: "পেপারলেস পরামর্শ",
    paperlessConsultationDesc: "পুরানো কাগজের প্রেসক্রিপশন বা ভারী ফাইল বহন করার দরকার নেই।",
    instantHospitalScanShare: "তাত্ক্ষণিক হাসপাতাল স্ক্যান ও শেয়ার",
    instantHospitalScanShareDesc: "কাগজের লাইনে না দাঁড়িয়ে সরাসরি তথ্য শেয়ার করতে ওপিডি কিওস্ক কিউআর কোড স্ক্যান করুন।",
    accurateDiagnosticTimeline: "নির্ভুল ডায়াগনস্টিক টাইমলাইন",
    accurateDiagnosticTimelineDesc: "ডাক্তাররা তাত্ক্ষণিকভাবে পূর্ববর্তী রক্ত পরীক্ষা, অ্যালার্জি ও অস্ত্রোপচারের ইতিহাস দেখতে পান।",
    accessibleViaMobileEmail: "মোবাইল বা ইমেলের মাধ্যমে অ্যাক্সেসযোগ্য",
    accessibleViaMobileEmailDesc: "ভারতে যেকোনো জায়গায় সহজ ওটিপি পুনরুদ্ধারের জন্য আপনার মোবাইল ও আধারের সাথে নিরাপদে সংযুক্ত।",
    noSpeechDetected: "কোনো কণ্ঠস্বর সনাক্ত হয়নি। অনুগ্রহ করে স্পষ্টভাবে বলুন।"
  }
};

const AppContext = createContext<AppContextType | undefined>(undefined);

export function AppProvider({ children }: { children: React.ReactNode }) {
  const [theme, setTheme] = useState<Theme>(() => {
    const saved = localStorage.getItem('theme');
    return (saved as Theme) || 'dark';
  });

  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const [isTranslating, setIsTranslating] = useState(false);
  const [translatingLanguageName, setTranslatingLanguageName] = useState('');
  const [dynamicTranslations, setDynamicTranslations] = useState<Record<string, Record<string, string>>>(() => {
    try {
      const cached = localStorage.getItem('mediSwiftDynamicTranslations');
      return cached ? JSON.parse(cached) : {};
    } catch {
      return {};
    }
  });

  useEffect(() => {
    localStorage.setItem('theme', theme);
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleTheme = () => {
    setTheme(prev => (prev === 'light' ? 'dark' : 'light'));
  };

  const setLanguage = async (newLang: Language) => {
    const fullName = LANGUAGE_NAMES[newLang];
    setTranslatingLanguageName(fullName);
    setLanguageState(newLang);

    // If language is en, hi, bn (which have instant built-in dictionaries) or already cached, switch instantly!
    const hasBuiltIn = newLang === 'en' || Boolean((translations as any)[newLang]);
    const hasCached = Boolean(dynamicTranslations[newLang]);

    if (hasBuiltIn || hasCached) {
      setIsTranslating(false);
      return;
    }

    // Dynamic translation via Gemini in background with fast feedback
    setIsTranslating(true);
    try {
      const response = await fetch('/api/translate/keys', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ keys: translations.en, targetLanguage: fullName })
      });
      if (response.ok) {
        const data = await response.json();
        if (data.keys) {
          setDynamicTranslations(prev => {
            const updated = { ...prev, [newLang]: data.keys };
            try {
              localStorage.setItem('mediSwiftDynamicTranslations', JSON.stringify(updated));
            } catch (e) {}
            return updated;
          });
        }
      }
    } catch (err) {
      console.error("Failed to dynamically translate interface keys:", err);
    } finally {
      setIsTranslating(false);
    }
  };

  const t = (key: string): string => {
    const langDict = dynamicTranslations[language] || (translations as any)[language] || translations['en'];
    return langDict?.[key] || (translations['en'] as any)?.[key] || key;
  };

  return (
    <AppContext.Provider value={{ 
      theme, 
      toggleTheme, 
      language, 
      setLanguage, 
      isTranslating, 
      setIsTranslating, 
      translatingLanguageName, 
      t 
    }}>
      {children}
    </AppContext.Provider>
  );
}

export function useAppContext() {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error('useAppContext must be used within an AppProvider');
  }
  return context;
}
